### ISSUE TITLE
[Migration]  Uncaught (in promise) ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by HAMADOns** [MikeCodeur/typescript-testing#1]
l'application se lance correctement avec l'apparition des erreurs suivantes :

<img width="950" alt="image" src="https://github.com/user-attachments/assets/b996b6a1-d42d-4496-ab9c-ee16fc1b7aab">

Uncaught (in promise) ReferenceError: describe is not defined
    at eval (03.ts:11:1)
    at (app-pages-browser)/src/__tests__/exercise/03.ts (http://localhost:3000/_next/static/chunks/app/(alone)/alone/exercise/%5BexerciseId%5D/page.js:556:1)
    at options.factory (webpack.js?v=1721150781034:716:31)
    at __webpack_require__ (webpack.js?v=1721150781034:37:33)
    at Function.fn (webpack.js?v=1721150781034:371:21)
eval @ 03.ts:11
(app-pages-browser)/./src/__tests__/exercise/03.ts @ page.js:556
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
fn @ webpack.js?v=1721150781034:371
Promise.then (async)
eval @ ?5609:6
(app-pages-browser)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-flight-client-entry-loader.js?modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Cimage-component.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Clink.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cshared%5Clib%5Clazy-dynamic%5Cdynamic-no-ssr.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5C(practice)%5Cpratice-content.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5Cmenu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cerror.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cfavicon.ico&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cstyles%5Cglobals.css&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ciframe.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cmode-toggle.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cmore%5Cmore-desktop.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cnavbar.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ctheme-provider.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Caccordion.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cdropdown-menu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cprogress.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cswitch.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctabs.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctooltip.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C01.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C02.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C03.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C04.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C05.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5Clibrary.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5C01.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Clib%5CexerciseHelper.tsx&server=false! @ page.js:149
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
__webpack_exec__ @ page.js:1755
(anonymous) @ page.js:1756
__webpack_require__.O @ webpack.js?v=1721150781034:86
webpackJsonpCallback @ webpack.js?v=1721150781034:1398
(anonymous) @ main-app.js?v=1721150781034:9Understand this error
01.ts:6 Uncaught (in promise) ReferenceError: test is not defined
    at eval (01.ts:6:1)
    at (app-pages-browser)/src/__tests__/final/01.ts (http://localhost:3000/_next/static/chunks/app/(alone)/alone/exercise/%5BexerciseId%5D/page.js:567:1)
    at options.factory (webpack.js?v=1721150781034:716:31)
    at __webpack_require__ (webpack.js?v=1721150781034:37:33)
    at Function.fn (webpack.js?v=1721150781034:371:21)
eval @ 01.ts:6
(app-pages-browser)/./src/__tests__/final/01.ts @ page.js:567
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
fn @ webpack.js?v=1721150781034:371
Promise.then (async)
eval @ ?5609:7
(app-pages-browser)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-flight-client-entry-loader.js?modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Cimage-component.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Clink.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cshared%5Clib%5Clazy-dynamic%5Cdynamic-no-ssr.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5C(practice)%5Cpratice-content.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5Cmenu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cerror.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cfavicon.ico&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cstyles%5Cglobals.css&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ciframe.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cmode-toggle.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cmore%5Cmore-desktop.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cnavbar.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ctheme-provider.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Caccordion.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cdropdown-menu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cprogress.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cswitch.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctabs.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctooltip.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C01.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C02.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C03.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C04.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C05.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5Clibrary.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5C01.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Clib%5CexerciseHelper.tsx&server=false! @ page.js:149
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
__webpack_exec__ @ page.js:1755
(anonymous) @ page.js:1756
__webpack_require__.O @ webpack.js?v=1721150781034:86
webpackJsonpCallback @ webpack.js?v=1721150781034:1398
(anonymous) @ main-app.js?v=1721150781034:9Understand this error
02.ts:6 Uncaught (in promise) ReferenceError: describe is not defined
    at eval (02.ts:6:1)
    at (app-pages-browser)/src/__tests__/final/02.ts (http://localhost:3000/_next/static/chunks/app/(alone)/alone/exercise/%5BexerciseId%5D/page.js:578:1)
    at options.factory (webpack.js?v=1721150781034:716:31)
    at __webpack_require__ (webpack.js?v=1721150781034:37:33)
    at Function.fn (webpack.js?v=1721150781034:371:21)
eval @ 02.ts:6
(app-pages-browser)/./src/__tests__/final/02.ts @ page.js:578
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
fn @ webpack.js?v=1721150781034:371
Promise.then (async)
eval @ ?5609:8
(app-pages-browser)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-flight-client-entry-loader.js?modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Cimage-component.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cclient%5Clink.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Cnode_modules%5C.pnpm%5Cnext%4014.0.4_%40babel%2Bcore%407.24.7_react-dom%4018.3.1_react%4018.3.1__react%4018.3.1%5Cnode_modules%5Cnext%5Cdist%5Cshared%5Clib%5Clazy-dynamic%5Cdynamic-no-ssr.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cexercise%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C01.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C02.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5C__tests__%5Cfinal%5C03.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5C(practice)%5Cpratice-content.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C_components%5C(app)%5Cmenu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cerror.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cfavicon.ico&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Capp%5C(course-app)%5Cstyles%5Cglobals.css&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ciframe.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cmode-toggle.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cmore%5Cmore-desktop.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Cnavbar%5Cnavbar.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Capp%5Ctheme-provider.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Caccordion.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cdropdown-menu.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cprogress.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Cswitch.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctabs.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Ccomponents%5Cui%5Ctooltip.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C01.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C02.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C03.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C04.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5C05.tsx&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cexercise%5Chelper%5Clibrary.ts&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5C01.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Cfinal%5Chelper%5CexerciseHelper.js&modules=C%3A%5CUsers%5Consha%5CDesktop%5CFINALISATION%20-%20MIGRATION%20REACT%5Ccourse-app%5Csrc%5Clib%5CexerciseHelper.tsx&server=false! @ page.js:149
options.factory @ webpack.js?v=1721150781034:716
__webpack_require__ @ webpack.js?v=1721150781034:37
__webpack_exec__ @ page.js:1755
(anonymous) @ page.js:1756
__webpack_require__.O @ webpack.js?v=1721150781034:86
webpackJsonpCallback @ webpack.js?v=1721150781034:1398
(anonymous) @ main-app.js?v=1721150781034:9Understand this error
03.ts:6 Uncaught (in promise) ReferenceError: beforeEach is not defined
    at eval (03.ts:6:1)
    at (app-pages-browser)/src/__tests__/final/03.ts (http://localhost:3000/_next/static/chunks/app/(alone)/alone/exercise/%5BexerciseId%5D/page.js:589:1)
    at options.factory (webpack.js?v=1721150781034:716:31)
    at __webpack_require__ (webpack.js?v=1721150781034:37:33)
    at Function.fn (webpack.js?v=1721150781034:371:21)

**Comment by HAMADOns** [comment]
Pas d'erreur après la dernière MAJ courseApp
